# Generated by Django 4.2.25 on 2026-04-30 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=180, verbose_name='عنوان')),
                ('slug', models.SlugField(max_length=180, unique=True, verbose_name='اسلاگ')),
                ('category', models.CharField(max_length=80, verbose_name='دسته\u200cبندی')),
                ('summary', models.TextField(verbose_name='خلاصه')),
                ('content', models.TextField(verbose_name='متن کامل')),
                ('reading_time', models.PositiveSmallIntegerField(default=5, verbose_name='زمان مطالعه (دقیقه)')),
                ('accent', models.CharField(default='gold', max_length=24, verbose_name='رنگ شاخص')),
                ('is_featured', models.BooleanField(default=False, verbose_name='مطلب ویژه')),
                ('is_published', models.BooleanField(default=True, verbose_name='منتشر شده')),
                ('published_at', models.DateTimeField(verbose_name='تاریخ انتشار')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'مطلب وبلاگ',
                'verbose_name_plural': 'مطالب وبلاگ',
                'ordering': ['-published_at', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ContactMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=120, verbose_name='نام و نام خانوادگی')),
                ('phone', models.CharField(blank=True, max_length=32, verbose_name='شماره تماس')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='ایمیل')),
                ('company', models.CharField(blank=True, max_length=120, verbose_name='نام شرکت')),
                ('subject', models.CharField(blank=True, max_length=160, verbose_name='موضوع')),
                ('message', models.TextField(verbose_name='پیام')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'پیام تماس با ما',
                'verbose_name_plural': 'پیام\u200cهای تماس با ما',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='FAQItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=220, verbose_name='سوال')),
                ('answer', models.TextField(verbose_name='پاسخ')),
                ('sort_order', models.PositiveSmallIntegerField(default=0, verbose_name='ترتیب')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
            ],
            options={
                'verbose_name': 'سوال متداول',
                'verbose_name_plural': 'سوالات متداول',
                'ordering': ['sort_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(default='سیتباک', max_length=80, verbose_name='نام سایت')),
                ('support_phone', models.CharField(blank=True, max_length=32, verbose_name='شماره پشتیبانی')),
                ('sales_phone', models.CharField(blank=True, max_length=32, verbose_name='شماره فروش')),
                ('support_email', models.EmailField(blank=True, max_length=254, verbose_name='ایمیل')),
                ('address', models.CharField(blank=True, max_length=255, verbose_name='آدرس')),
                ('working_hours', models.CharField(blank=True, max_length=120, verbose_name='ساعات پاسخ\u200cگویی')),
                ('footer_about', models.TextField(blank=True, verbose_name='توضیح کوتاه فوتر')),
                ('whatsapp_number', models.CharField(blank=True, max_length=32, verbose_name='شماره واتساپ')),
                ('telegram_url', models.URLField(blank=True, verbose_name='لینک تلگرام')),
                ('instagram_url', models.URLField(blank=True, verbose_name='لینک اینستاگرام')),
                ('linkedin_url', models.URLField(blank=True, verbose_name='لینک لینکدین')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'تنظیمات سایت',
                'verbose_name_plural': 'تنظیمات سایت',
            },
        ),
    ]
