# Generated by Django 4.2.25 on 2026-05-16 05:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0012_bale_bot'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='leadrequest',
            options={'ordering': ['-created_at'], 'verbose_name': 'لید / درخواست مشاوره', 'verbose_name_plural': 'لیدها و درخواست\u200cهای مشاوره'},
        ),
        migrations.RenameIndex(
            model_name='pagecontentitem',
            new_name='landing_pag_page_ke_3c77a1_idx',
            old_name='landing_pag_page_ke_2ec4c4_idx',
        ),
        migrations.RenameIndex(
            model_name='pagecontentitem',
            new_name='landing_pag_sort_or_0f0c30_idx',
            old_name='landing_pag_sort_or_3883ef_idx',
        ),
    ]
