# Generated by Django 4.2.25 on 2026-05-16 09:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0013_alter_leadrequest_options_and_more'),
        ('landing', '0013_update_home_satisfaction_stat'),
    ]

    operations = [
    ]
