# Generated by Django 4.2.25 on 2026-05-17 05:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0014_merge_20260516_1242'),
        ('landing', '0022_page_builder_section'),
    ]

    operations = [
    ]
