# Generated by Django 4.2.25 on 2026-05-17 05:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0023_content_studio_fields'),
        ('landing', '0023_merge_20260517_0856'),
    ]

    operations = [
    ]
