# Generated by Django 4.2.25 on 2026-05-17 05:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0024_merge_20260517_0907'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='blogpost',
            name='blog_content_status_idx',
        ),
        migrations.RemoveIndex(
            model_name='faqitem',
            name='faq_category_active_idx',
        ),
    ]
