# Generated by Django 4.2.25 on 2026-05-17 05:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0024_site_redirect'),
        ('landing', '0025_remove_blogpost_blog_content_status_idx_and_more'),
    ]

    operations = [
    ]
